FROM ${BASE_NAMESPACE}/${BASE_IMAGE}:${BASE_TAG}

USER root

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y --no-install-recommends bash jq libxss1 && \
    rm -rf /tmp/* && \
    rm -rf /var/lib/apt/lists/*

USER node

WORKDIR /src

ENTRYPOINT ["/src/entrypoint.sh"]

CMD ["./go.sh"]

COPY . /src
